---
name: Boris Fazio
position: "Analista de Datos"
address: "Métodos cuantitativos aplicados a salud pública e investigación biomédica"
phone: +51 987 807 758
www: bmfazio.github.io
email: "boris.fazio@outlook.com"
#twitter: bmfazio
github: bmfazio
linkedin: bmfazio
date: "`r format(Sys.time(), '%B %Y')`"
output: (function (...) {;template <- here::here("cv-template.tex");vitae::cv_document(..., template = template, citation_package = "biblatex",latex_engine = "xelatex")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)

#limape <- "Lima, Perú"
limape <- NA
pucp <- "Pontificia Universidad Católica del Perú"
upch <- "Universidad Peruana Cayetano Heredia"
unicef <- "UNICEF"
ciisss <- "Centro de Investigación Interdisciplinaria en Sexualidad, Sida y Sociedad"
minsa <- "Ministerio de Salud"
midis <- "Ministerio de Desarrollo e Inclusión Social"
faspa <- "Facultad de Salud Pública y Administración"

m_stat <- "Magister en Estadística"
m_stat.date <- "Mar. 2017 - "
m_epid <- "Maestría en Ciencias en Investigación Epidemiológica"
m_epid.date <- "Mar. 2015 - Dic. 2015"
b_biol <- "Bachiller en Ciencias con mención en Biología"
b_biol.date <- "Mar. 2009 - Dic. 2014"


```

# Experiencia

```{r}
tribble(
  ~ position, ~ company, ~ loc, ~ dates, ~ details,
  "Analista de medición (Consultoría)", unicef, limape, "Ago. 2018 -",
  "Integración de datos de encuestas nacionales y bases de datos administrativas para medición de indicadores",
  "Analista de medición (Consultoría)", unicef, limape, "Ago. 2018 -",
  "Implementación de procedimientos reproducibles para limpieza de datos y generación de reportes",
  "Analista de medición (Consultoría)", unicef, limape, "Ago. 2018 -",
  "Revisión de literatura sobre medición del bienestar adolescente",
  
  "Analista estadístico", minsa, limape, "Oct. 2016 - May. 2018",
  "Cruce de múltiples bases administrativas, permitió identificar más de 100 000 niños con tratamiento de anemia incompleto",
  "Analista Estadístico", minsa, limape, "Oct. 2016 - May. 2018",
  "Participación en rediseño de aplicativo para monitoreo de indicadores de desempeño, permitió redistribuir labores de entrada de datos de nuestro equipo de cinco personas hacia más de 200 puntos de digitación a nivel nacional",
  "Analista Estadístico", minsa, limape, "Oct. 2016 - May. 2018",
  "Soporte estadístico en diseño de esquemas de muestreo y selección de tamaño de muestra para encuestas nacionales",
  
  "Analista de datos (Consultoría)", midis, limape, "Dic. 2017 - Feb. 2018",
  "Implementación de reportes automáticos para monitoreo de intervenciones de salud",
  
  "Asistente de prácticas", paste(faspa, "--", upch), limape, "Mar. 2017 - Dic. 2017",
  "Tutorías para cursos de maestría en bioestadística y epidemiología",
  "Asistente de prácticas", paste(faspa, "--", upch), limape, "Mar. 2017 - Dic. 2017",
  "Apoyo a estudiantes de maestría para definir preguntas de investigación y plan de análisis",
  
  "Asistente de proyectos", paste(faspa, "--", upch), limape, "Dic. 2014 - Dic. 2016",
  "Generación de reportes y recomendaciones periódicas para minimizar errores de registro de datos de estudios en curso",
  "Asistente de proyectos", paste(faspa, "--", upch), limape, "Dic. 2014 - Dic. 2016",
  "Asistencia logística a investigadores",
  
  "Administrador de datos", ciisss, limape, "Sep. 2015 - Oct. 2016",
  "Generación automática de reportes de retención para estudio de cohorte",
  "Administrador de datos", ciisss, limape, "Sep. 2015 - Oct. 2016",
  "Apoyo a colegas para análisis estadístico de sus estudios",
  "Administrador de datos", ciisss, limape, "Sep. 2015 - Oct. 2016",
  "Limpieza de datos y mejora de la documentación de procesos"
) %>% 
  detailed_entries(company, dates, position, loc, details)
```

# Educación

```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  m_stat, pucp, limape, m_stat.date,
  "Pendiente revisión de tesis, egresado (Puesto: 1/38)",
  m_epid, upch, limape, m_epid.date,
  "Egresado de maestría",
  b_biol, upch, limape, b_biol.date,
  NA
) %>% 
  detailed_entries(uni, dates, degree, loc, details)
```

# Habilidades

\begin{cvskills}
\cvskill{Análisis de datos}{Modelos jerárquicos, análisis de sobrevivencia, modelamiento con ecuaciones estructurales, análisis y diseño de encuestas}
\cvskill{Programación}{R, SQL, Python, JavaScript}
\cvskill{Lenguajes}{Español, Inglés}
\end{cvskills}

\pagebreak

# Publicaciones

```{r}
tribble(
  ~ details,
  "\\textbf{Allan-Blitz LT et al.} \\textit{The Development of an Online Risk Calculator for the Prediction of Future Syphilis among a High-Risk Cohort of Men Who Have Sex with Men and Transgender Women in Lima, Peru.} Sexual Health, 2018.",
  "\\textbf{García PJ et al.} \\textit{Sexual health knowledge and practices and STI/HIV prevalence among long-distance truck drivers in Peru.} SAGE Open Medicine, 2017.",
  "\\textbf{Egoavil MS et al.} \\textit{Qualitative Study for the Development of a Telemedicine System in Palliative Care.} Palliative Medicine and Hospice Care, 2017."
) %>%
  brief_entries(what = details, .protect = FALSE)
```